import json

# Save chunk 1 (normalized from agent output)
chunk1 = {
  "nodes": [
    {"id":"paper_0047","label":"FGS-SLAM","file_type":"document","source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0050","label":"GI-SLAM","file_type":"document","source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0051","label":"STAMICS","file_type":"document","source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0053","label":"FGO-SLAM","file_type":"document","source_file":"0058_[SLAM]_FGO-SLAM Online Co-Design Optimization of Sensing, Computing, and Control for Gaussi.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0054","label":"Dy3DGS-SLAM","file_type":"document","source_file":"0060_[SLAM]_Dy3DGS-SLAM Dynamic 3D Gaussians for Multi-Session SLAM.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0061","label":"4DTAM","file_type":"document","source_file":"0062_[SLAM]_4DTAM Non-Rigid Object Tracking and Reconstruction by 4D Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0069","label":"DiskChunGS","file_type":"document","source_file":"0064_[SLAM]_DiskChunkGS Disk-Shaped Chunks for Gaussian Splatting-Based Point Cloud Reconstructi.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0081","label":"NeuralGrasps","file_type":"document","source_file":"0069_[Robotics]_NeuralGrasps Learning Implicit Representations for Grasping of Unknown Objects.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0082","label":"ObjectFolder 1.0","file_type":"document","source_file":"0071_[Robotics]_ObjectFolder A Dataset of Objects with Implicit Visual, Auditory, and Tactile Re.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0094","label":"CLIP-Fields","file_type":"document","source_file":"0075_[Robotics]_CLIP-Fields Open-label semantic navigation with pre-trained VLMs and language gro.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0095","label":"NeRF-VINS","file_type":"document","source_file":"0077_[Robotics]_NeRF-VINS A Real-time and Robust Back-End for Inertial Navigation Systems Using.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0097","label":"GaussNav","file_type":"document","source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"paper_0102","label":"ActiveSplat","file_type":"document","source_file":"0096_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction Through Active Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_3DGS","label":"3D Gaussian Splatting","file_type":"concept","source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_NeRF","label":"Neural Radiance Fields","file_type":"concept","source_file":"0071_[Robotics]_ObjectFolder A Dataset of Objects with Implicit Visual, Auditory, and Tactile Re.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_SDF","label":"Signed Distance Fields","file_type":"concept","source_file":"0069_[Robotics]_NeuralGrasps Learning Implicit Representations for Grasping of Unknown Objects.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_ORBSLAM3","label":"ORB-SLAM3","file_type":"concept","source_file":"0058_[SLAM]_FGO-SLAM Online Co-Design Optimization of Sensing, Computing, and Control for Gaussi.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_SAM","label":"Segment Anything Model","file_type":"concept","source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_CLIP","label":"CLIP","file_type":"concept","source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"method_IMU","label":"IMU Integration","file_type":"concept","source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_TUM","label":"TUM-RGBD","file_type":"concept","source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_Replica","label":"Replica","file_type":"concept","source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_EuRoC","label":"EuRoC MAV","file_type":"concept","source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_HM3D","label":"HM3D","file_type":"concept","source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_ScanNet","label":"ScanNet","file_type":"concept","source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"metric_ATE","label":"ATE RMSE","file_type":"concept","source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"metric_SPL","label":"SPL","file_type":"concept","source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
  ],
  "edges": [
    {"source":"paper_0047","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"weight":1.0},
    {"source":"paper_0047","target":"dataset_TUM","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"weight":1.0},
    {"source":"paper_0047","target":"dataset_Replica","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"weight":1.0},
    {"source":"paper_0047","target":"metric_ATE","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"weight":1.0},
    {"source":"paper_0050","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"weight":1.0},
    {"source":"paper_0050","target":"method_IMU","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"weight":1.0},
    {"source":"paper_0050","target":"dataset_EuRoC","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"weight":1.0},
    {"source":"paper_0050","target":"metric_ATE","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0050_[SLAM]_GI-SLAM Gaussian-Inertial SLAM.md","source_location":None,"weight":1.0},
    {"source":"paper_0051","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"weight":1.0},
    {"source":"paper_0051","target":"method_SAM","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"weight":1.0},
    {"source":"paper_0051","target":"method_CLIP","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"weight":1.0},
    {"source":"paper_0051","target":"dataset_Replica","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"weight":1.0},
    {"source":"paper_0051","target":"dataset_ScanNet","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0053_[SLAM]_STAMICS Splat, Track And Map with Integrated Consistency and Semantics for Dense RGB-.md","source_location":None,"weight":1.0},
    {"source":"paper_0053","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0058_[SLAM]_FGO-SLAM Online Co-Design Optimization of Sensing, Computing, and Control for Gaussi.md","source_location":None,"weight":1.0},
    {"source":"paper_0053","target":"method_ORBSLAM3","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0058_[SLAM]_FGO-SLAM Online Co-Design Optimization of Sensing, Computing, and Control for Gaussi.md","source_location":None,"weight":1.0},
    {"source":"paper_0054","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0060_[SLAM]_Dy3DGS-SLAM Dynamic 3D Gaussians for Multi-Session SLAM.md","source_location":None,"weight":1.0},
    {"source":"paper_0081","target":"method_SDF","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0069_[Robotics]_NeuralGrasps Learning Implicit Representations for Grasping of Unknown Objects.md","source_location":None,"weight":1.0},
    {"source":"paper_0082","target":"method_NeRF","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0071_[Robotics]_ObjectFolder A Dataset of Objects with Implicit Visual, Auditory, and Tactile Re.md","source_location":None,"weight":1.0},
    {"source":"paper_0094","target":"method_CLIP","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0075_[Robotics]_CLIP-Fields Open-label semantic navigation with pre-trained VLMs and language gro.md","source_location":None,"weight":1.0},
    {"source":"paper_0094","target":"dataset_HM3D","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0075_[Robotics]_CLIP-Fields Open-label semantic navigation with pre-trained VLMs and language gro.md","source_location":None,"weight":1.0},
    {"source":"paper_0097","target":"method_3DGS","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"weight":1.0},
    {"source":"paper_0097","target":"method_CLIP","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"weight":1.0},
    {"source":"paper_0097","target":"dataset_HM3D","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"weight":1.0},
    {"source":"paper_0097","target":"metric_SPL","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0079_[Robotics]_GaussNav Gaussian Splatting for Visual Navigation.md","source_location":None,"weight":1.0},
    {"source":"paper_0047","target":"paper_0050","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md","source_location":None,"weight":0.85},
    {"source":"paper_0094","target":"paper_0097","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.82,"source_file":"0075_[Robotics]_CLIP-Fields Open-label semantic navigation with pre-trained VLMs and language gro.md","source_location":None,"weight":0.82},
  ],
  "hyperedges": [
    {"id":"he_semantic_slam","label":"Semantic 3DGS SLAM Systems","nodes":["paper_0047","paper_0050","paper_0051","paper_0053"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.85,"source_file":"0047_[SLAM]_FGS-SLAM Fourier-based Gaussian Splatting for Real-time SLAM with Sparse and Dense Map.md"},
  ],
  "input_tokens": 87420,
  "output_tokens": 6180
}

with open('.graphify_chunk_01_result.json', 'w', encoding='utf-8') as f:
    json.dump(chunk1, f, ensure_ascii=False)
print(f'chunk 1 saved: {len(chunk1["nodes"])} nodes, {len(chunk1["edges"])} edges')

# Save chunk 2 (minimal summary from agent output)
chunk2 = {
  "nodes": [
    {"id":"0100_HGSPlanner","label":"HGS-Planner","file_type":"document","source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0101_RTGuIDE","label":"RT-GuIDE","file_type":"document","source_file":"0101_[Robotics]_RT-GuIDE Real-Time Gaussian splatting for Information-Driven Explorat.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0102_ActiveSplat","label":"ActiveSplat","file_type":"document","source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0104_SAFERSplat","label":"SAFER-Splat","file_type":"document","source_file":"0104_[Robotics]_SAFER-Splat A Control Barrier Function for Safe Navigation with Online G.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0106_ActiveGS","label":"ActiveGS","file_type":"document","source_file":"0106_[Robotics]_ActiveGS Active Scene Reconstruction using Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0128_GSLoc","label":"GSLoc","file_type":"document","source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0129_LoGS","label":"LoGS","file_type":"document","source_file":"0129_[Robotics]_LoGS Visual Localization via Gaussian Splatting with Fewer Traini.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"0130_GSplatLoc","label":"SplatLoc","file_type":"document","source_file":"0130_[Robotics]_SplatLoc 3D Gaussian Splatting-based Visual Localization for Augmente.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_3DGS_c2","label":"3D Gaussian Splatting","file_type":"concept","source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_NBV_c2","label":"Next-Best-View Planning","file_type":"concept","source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_CBF_c2","label":"Control Barrier Function","file_type":"concept","source_file":"0104_[Robotics]_SAFER-Splat A Control Barrier Function for Safe Navigation with Online G.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_Gibson_c2","label":"Gibson Dataset","file_type":"concept","source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_MP3D_c2","label":"Matterport3D Dataset","file_type":"concept","source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_Replica_c2","label":"Replica Dataset","file_type":"concept","source_file":"0106_[Robotics]_ActiveGS Active Scene Reconstruction using Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dataset_7Scenes_c2","label":"7-Scenes Dataset","file_type":"concept","source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"metric_PoseError_c2","label":"Rotation/Translation Pose Error","file_type":"concept","source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
  ],
  "edges": [
    {"source":"0100_HGSPlanner","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"weight":1.0},
    {"source":"0100_HGSPlanner","target":"concept_NBV_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"weight":1.0},
    {"source":"0100_HGSPlanner","target":"dataset_MP3D_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"dataset_Gibson_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"dataset_MP3D_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"0100_HGSPlanner","relation":"cites","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"0101_RTGuIDE","relation":"cites","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0102_ActiveSplat","target":"0106_ActiveGS","relation":"cites","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0102_[Robotics]_ActiveSplat High-Fidelity Scene Reconstruction through Active Gaussian S.md","source_location":None,"weight":1.0},
    {"source":"0104_SAFERSplat","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0104_[Robotics]_SAFER-Splat A Control Barrier Function for Safe Navigation with Online G.md","source_location":None,"weight":1.0},
    {"source":"0104_SAFERSplat","target":"concept_CBF_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0104_[Robotics]_SAFER-Splat A Control Barrier Function for Safe Navigation with Online G.md","source_location":None,"weight":1.0},
    {"source":"0106_ActiveGS","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0106_[Robotics]_ActiveGS Active Scene Reconstruction using Gaussian Splatting.md","source_location":None,"weight":1.0},
    {"source":"0106_ActiveGS","target":"dataset_Replica_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0106_[Robotics]_ActiveGS Active Scene Reconstruction using Gaussian Splatting.md","source_location":None,"weight":1.0},
    {"source":"0128_GSLoc","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"weight":1.0},
    {"source":"0128_GSLoc","target":"dataset_Replica_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"weight":1.0},
    {"source":"0128_GSLoc","target":"metric_PoseError_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"weight":1.0},
    {"source":"0129_LoGS","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0129_[Robotics]_LoGS Visual Localization via Gaussian Splatting with Fewer Traini.md","source_location":None,"weight":1.0},
    {"source":"0129_LoGS","target":"dataset_7Scenes_c2","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0129_[Robotics]_LoGS Visual Localization via Gaussian Splatting with Fewer Traini.md","source_location":None,"weight":1.0},
    {"source":"0130_GSplatLoc","target":"concept_3DGS_c2","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"0130_[Robotics]_SplatLoc 3D Gaussian Splatting-based Visual Localization for Augmente.md","source_location":None,"weight":1.0},
    {"source":"0100_HGSPlanner","target":"0101_RTGuIDE","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"weight":0.9},
    {"source":"0100_HGSPlanner","target":"0102_ActiveSplat","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md","source_location":None,"weight":0.9},
    {"source":"0128_GSLoc","target":"0129_LoGS","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"weight":0.9},
    {"source":"0128_GSLoc","target":"0130_GSplatLoc","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md","source_location":None,"weight":0.9},
  ],
  "hyperedges": [
    {"id":"hyperedge_active_reconstruction","label":"Active 3DGS Scene Reconstruction","nodes":["0100_HGSPlanner","0101_RTGuIDE","0102_ActiveSplat","0106_ActiveGS"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.9,"source_file":"0100_[Robotics]_HGS-Planner Hierarchical Planning Framework for Active Scene Reconstruct.md"},
    {"id":"hyperedge_3dgs_localization","label":"3DGS Visual Localization","nodes":["0128_GSLoc","0129_LoGS","0130_GSplatLoc"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.85,"source_file":"0128_[Robotics]_GSLoc Visual Localization with 3D Gaussian Splatting.md"},
  ],
  "input_tokens": 0,
  "output_tokens": 0
}

with open('.graphify_chunk_02_result.json', 'w', encoding='utf-8') as f:
    json.dump(chunk2, f, ensure_ascii=False)
print(f'chunk 2 saved: {len(chunk2["nodes"])} nodes, {len(chunk2["edges"])} edges')

print("All chunks saved successfully")
